package sbnz.integracija;
import sbnz.integracija.example.facts.*
import sbnz.integracija.example.enums.*

rule "Classify Request By Age OLD"
	agenda-group "age"
	when
	    $request: Request( age >= 55 && age < 200 )
	then
	    modify($request){ setAgeCategory(AgeCategory.OLD); }
	end

rule "Classify Request By Age ADULT"
	agenda-group "age"
	when
	    $request: Request( age >= 30 && age < 55 )
	then
	    modify($request){ setAgeCategory(AgeCategory.ADULT); }
	end

rule "Classify Request By Age YOUNG"
	agenda-group "age"
	when
	    $request: Request( age >= 0 && age < 30 )
	then
	    modify($request){ setAgeCategory(AgeCategory.YOUNG); }
	end


