package sbnz.integracija;

import sbnz.integracija.example.facts.*
import sbnz.integracija.example.enums.*

rule "Classify Request By Age OLD"
	agenda-group "age"
	when
	    $request: Request( age >= 60 && age < 2147483647 )
	then
	    modify($request){ setAgeCategory(AgeCategory.OLD); }
	end

rule "Classify Request By Age ADULT"
	agenda-group "age"
	when
	     $request: Request( age >= 25 && age < 60 )
	then
	    modify($request){ setAgeCategory(AgeCategory.ADULT); }
	end

rule "Classify Request By Age YOUNG"
	agenda-group "age"
	when
	    $request: Request( age >= 0 && age < 25 ) 
	then
	    modify($request){ setAgeCategory(AgeCategory.YOUNG); }
	end